# Advance IOT on Agriculture Dataset

In [42]:
import pandas as pd
import seaborn as sb
import numpy as np
import matplotlib.pyplot as plt
import missingno as msno
import os
import sys

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier 
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [24]:
df = pd.read_csv("D:\Open Classroom\Datasets\Advanced IoT Agriculture 2024\Advanced_IoT_Dataset.csv")
df.head()

Random   Average  of chlorophyll in the plant (ACHP)  \
0     R1                                     34.533468   
1     R1                                     34.489028   
2     R2                                     33.100405   
3     R1                                     34.498319   
4     R3                                     36.297008   

    Plant height rate (PHR)  \
0                 54.566983   
1                 54.567692   
2                 67.067344   
3                 54.559049   
4                 45.588894   

   Average wet weight of the growth vegetative (AWWGV)  \
0                                           1.147449     
1                                           1.149530     
2                                           1.104647     
3                                           1.137759     
4                                           1.363205     

   Average leaf area of the plant (ALAP)  \
0                            1284.229549   
1                            1284.247744   
2                            1009.208996   
3                            1284.227623   
4                             981.470310   

   Average number of plant leaves (ANPL)  Average root diameter (ARD)  \
0                               4.999713                    16.274918   
1                               5.024259                    16.269452   
2                               5.007652                    15.980760   
3                               4.991501                    16.276710   
4                               4.003682                    16.979894   

    Average dry weight of the root (ADWR)  \
0                                1.706810   
1                                1.700930   
2                                1.185391   
3                                1.716396   
4                                0.777428   

    Percentage of dry matter for vegetative growth (PDMVG)  \
0                                          18.399982         
1                                          18.398289         
2                                          19.398789         
3                                          18.413613         
4                                          31.423772         

   Average root length (ARL)  Average wet weight of the root (AWWR)  \
0                  19.739037                               2.949240   
1                  19.758836                               2.943137   
2                  20.840822                               2.861635   
3                  19.736098                               2.946784   
4                  17.331894                               2.766242   

    Average dry weight of vegetative plants (ADWV)  \
0                                         0.209251   
1                                         0.216154   
2                                         0.200113   
3                                         0.223092   
4                                         0.424172   

   Percentage of dry matter for root growth (PDMRG) Class  
0                                         57.633906    SA  
1                                         57.633697    SA  
2                                         41.289875    SA  
3                                         57.645661    SA  
4                                         27.898619    SA

In [25]:
df.shape

(30000, 14)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 14 columns):
 #   Column                                                   Non-Null Count  Dtype  
---  ------                                                   --------------  -----  
 0   Random                                                   30000 non-null  object 
 1    Average  of chlorophyll in the plant (ACHP)             30000 non-null  float64
 2    Plant height rate (PHR)                                 30000 non-null  float64
 3   Average wet weight of the growth vegetative (AWWGV)      30000 non-null  float64
 4   Average leaf area of the plant (ALAP)                    30000 non-null  float64
 5   Average number of plant leaves (ANPL)                    30000 non-null  float64
 6   Average root diameter (ARD)                              30000 non-null  float64
 7    Average dry weight of the root (ADWR)                   30000 non-null  float64
 8    Percentage of dry matter 

In [27]:
df.describe().round()

Average  of chlorophyll in the plant (ACHP)   Plant height rate (PHR)  \
count                                       30000.0                   30000.0   
mean                                           38.0                      59.0   
std                                             4.0                      12.0   
min                                            33.0                      37.0   
25%                                            34.0                      51.0   
50%                                            37.0                      56.0   
75%                                            42.0                      67.0   
max                                            46.0                      77.0   

       Average wet weight of the growth vegetative (AWWGV)  \
count                                            30000.0     
mean                                                 1.0     
std                                                  0.0     
min                                                  1.0     
25%                                                  1.0     
50%                                                  1.0     
75%                                                  2.0     
max                                                  2.0     

       Average leaf area of the plant (ALAP)  \
count                                30000.0   
mean                                  1064.0   
std                                    261.0   
min                                    658.0   
25%                                    876.0   
50%                                   1009.0   
75%                                   1244.0   
max                                   1751.0   

       Average number of plant leaves (ANPL)  Average root diameter (ARD)  \
count                                30000.0                      30000.0   
mean                                     4.0                         16.0   
std                                      1.0                          3.0   
min                                      3.0                         11.0   
25%                                      3.0                         14.0   
50%                                      4.0                         16.0   
75%                                      4.0                         18.0   
max                                      5.0                         23.0   

        Average dry weight of the root (ADWR)  \
count                                 30000.0   
mean                                      1.0   
std                                       0.0   
min                                       0.0   
25%                                       1.0   
50%                                       1.0   
75%                                       1.0   
max                                       2.0   

        Percentage of dry matter for vegetative growth (PDMVG)  \
count                                            30000.0         
mean                                                23.0         
std                                                 10.0         
min                                                  8.0         
25%                                                 15.0         
50%                                                 22.0         
75%                                                 28.0         
max                                                 44.0         

       Average root length (ARL)  Average wet weight of the root (AWWR)  \
count                    30000.0                                30000.0   
mean                        18.0                                    3.0   
std                          3.0                                    1.0   
min                         12.0                                    1.0   
25%                         16.0                                    2.0   
50%                         18.0                                    3.0   
75%                         20

In [28]:
df.head()

Random   Average  of chlorophyll in the plant (ACHP)  \
0     R1                                     34.533468   
1     R1                                     34.489028   
2     R2                                     33.100405   
3     R1                                     34.498319   
4     R3                                     36.297008   

    Plant height rate (PHR)  \
0                 54.566983   
1                 54.567692   
2                 67.067344   
3                 54.559049   
4                 45.588894   

   Average wet weight of the growth vegetative (AWWGV)  \
0                                           1.147449     
1                                           1.149530     
2                                           1.104647     
3                                           1.137759     
4                                           1.363205     

   Average leaf area of the plant (ALAP)  \
0                            1284.229549   
1                            1284.247744   
2                            1009.208996   
3                            1284.227623   
4                             981.470310   

   Average number of plant leaves (ANPL)  Average root diameter (ARD)  \
0                               4.999713                    16.274918   
1                               5.024259                    16.269452   
2                               5.007652                    15.980760   
3                               4.991501                    16.276710   
4                               4.003682                    16.979894   

    Average dry weight of the root (ADWR)  \
0                                1.706810   
1                                1.700930   
2                                1.185391   
3                                1.716396   
4                                0.777428   

    Percentage of dry matter for vegetative growth (PDMVG)  \
0                                          18.399982         
1                                          18.398289         
2                                          19.398789         
3                                          18.413613         
4                                          31.423772         

   Average root length (ARL)  Average wet weight of the root (AWWR)  \
0                  19.739037                               2.949240   
1                  19.758836                               2.943137   
2                  20.840822                               2.861635   
3                  19.736098                               2.946784   
4                  17.331894                               2.766242   

    Average dry weight of vegetative plants (ADWV)  \
0                                         0.209251   
1                                         0.216154   
2                                         0.200113   
3                                         0.223092   
4                                         0.424172   

   Percentage of dry matter for root growth (PDMRG) Class  
0                                         57.633906    SA  
1                                         57.633697    SA  
2                                         41.289875    SA  
3                                         57.645661    SA  
4                                         27.898619    SA

In [29]:
df.isnull().sum()

Random                                                     0
 Average  of chlorophyll in the plant (ACHP)               0
 Plant height rate (PHR)                                   0
Average wet weight of the growth vegetative (AWWGV)        0
Average leaf area of the plant (ALAP)                      0
Average number of plant leaves (ANPL)                      0
Average root diameter (ARD)                                0
 Average dry weight of the root (ADWR)                     0
 Percentage of dry matter for vegetative growth (PDMVG)    0
Average root length (ARL)                                  0
Average wet weight of the root (AWWR)                      0
 Average dry weight of vegetative plants (ADWV)            0
Percentage of dry matter for root growth (PDMRG)           0
Class                                                      0
dtype: int64

In [30]:
df['Random'].value_counts()

Random
R1    10045
R3     9996
R2     9959
Name: count, dtype: int64

In [31]:
le = LabelEncoder()

df['Random'] = le.fit_transform(df['Random'])
df.head()

Random   Average  of chlorophyll in the plant (ACHP)  \
0       0                                     34.533468   
1       0                                     34.489028   
2       1                                     33.100405   
3       0                                     34.498319   
4       2                                     36.297008   

    Plant height rate (PHR)  \
0                 54.566983   
1                 54.567692   
2                 67.067344   
3                 54.559049   
4                 45.588894   

   Average wet weight of the growth vegetative (AWWGV)  \
0                                           1.147449     
1                                           1.149530     
2                                           1.104647     
3                                           1.137759     
4                                           1.363205     

   Average leaf area of the plant (ALAP)  \
0                            1284.229549   
1                            1284.247744   
2                            1009.208996   
3                            1284.227623   
4                             981.470310   

   Average number of plant leaves (ANPL)  Average root diameter (ARD)  \
0                               4.999713                    16.274918   
1                               5.024259                    16.269452   
2                               5.007652                    15.980760   
3                               4.991501                    16.276710   
4                               4.003682                    16.979894   

    Average dry weight of the root (ADWR)  \
0                                1.706810   
1                                1.700930   
2                                1.185391   
3                                1.716396   
4                                0.777428   

    Percentage of dry matter for vegetative growth (PDMVG)  \
0                                          18.399982         
1                                          18.398289         
2                                          19.398789         
3                                          18.413613         
4                                          31.423772         

   Average root length (ARL)  Average wet weight of the root (AWWR)  \
0                  19.739037                               2.949240   
1                  19.758836                               2.943137   
2                  20.840822                               2.861635   
3                  19.736098                               2.946784   
4                  17.331894                               2.766242   

    Average dry weight of vegetative plants (ADWV)  \
0                                         0.209251   
1                                         0.216154   
2                                         0.200113   
3                                         0.223092   
4                                         0.424172   

   Percentage of dry matter for root growth (PDMRG) Class  
0                                         57.633906    SA  
1                                         57.633697    SA  
2                                         41.289875    SA  
3                                         57.645661    SA  
4                                         27.898619    SA

In [32]:
x = df.drop(columns = ['Class'])
y = df['Class']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2, random_state=40)

print('x train', x_train.shape)
print('x test', x_test.shape)
print('y train', y_train.shape)
print('y test', y_test.shape)

x train (24000, 13)
x test (6000, 13)
y train (24000,)
y test (6000,)


In [34]:
models = {
    'Decision Tree': DecisionTreeClassifier(),
    'Support Vector Classifier': SVC(),
    'Random Forest Classifier': RandomForestClassifier(),
    'Gradient Boost Classifier': GradientBoostingClassifier()
}

In [46]:
for model_name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print('------' + model_name + '-------')
    print('acc score ', accuracy_score(y_pred, y_test))
    print('precision score ', precision_score(y_pred, y_test, average='micro'))
    print('recall score ', recall_score(y_pred, y_test, average='micro'))
    print('confusion matrix \n', confusion_matrix(y_pred, y_test))
    print('')

------Decision Tree-------
acc score  1.0
precision score  1.0
recall score  1.0
confusion matrix 
 [[ 998    0    0    0    0    0]
 [   0  980    0    0    0    0]
 [   0    0 1030    0    0    0]
 [   0    0    0  991    0    0]
 [   0    0    0    0 1006    0]
 [   0    0    0    0    0  995]]

------Support Vector Classifier-------
acc score  0.8283333333333334
precision score  0.8283333333333334
recall score  0.8283333333333334
confusion matrix 
 [[998   0   0   0   0   0]
 [  0 980 343   0   0   0]
 [  0   0 687   0 335   0]
 [  0   0   0 991   0 352]
 [  0   0   0   0 671   0]
 [  0   0   0   0   0 643]]

------Random Forest Classifier-------
acc score  1.0
precision score  1.0
recall score  1.0
confusion matrix 
 [[ 998    0    0    0    0    0]
 [   0  980    0    0    0    0]
 [   0    0 1030    0    0    0]
 [   0    0    0  991    0    0]
 [   0    0    0    0 1006    0]
 [   0    0    0    0    0  995]]

------Gradient Boost Classifier-------
acc score  1.0
precision scor